# Generated by Django 3.0.2 on 2021-02-01 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210130_1533'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
