# Generated by Django 3.0.2 on 2021-02-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField()),
                ('tour_date', models.DateTimeField()),
                ('author', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('review', models.IntegerField()),
            ],
        ),
    ]
