# Generated by Django 3.0.2 on 2021-02-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='date_posted',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_date',
            field=models.DateField(blank=True),
        ),
    ]
