# Generated by Django 3.0.2 on 2021-02-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0002_auto_20210201_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='date_posted',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_date',
            field=models.DateField(null=True),
        ),
    ]
