# Generated by Django 3.0.2 on 2021-02-01 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0003_auto_20210201_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='author',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='content',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='review',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='tour_date',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='type',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateField(null=True)),
                ('tour_date', models.DateField(null=True)),
                ('author', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('star', models.IntegerField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape.Tour')),
            ],
        ),
    ]
